INSERT INTO Airport
VALUES
('AEP', 'Aeroparque Jorge Newbery', 'Argentina', NULL),
('AMS', 'Amsterdam Airport Schiphol', 'Netherlands', NULL),
('ASB', 'Ashgabat International', 'Turkmenistan', NULL),
('ASU', 'Silvio Pettirossi International', 'Paraguay', NULL),
('ATH', 'Athens International', 'Greece', NULL),
('ATL', 'Hartsfield-Jackson Atlanta', 'United States', 'GA'),
('BDO', 'Husein Sastranegara', 'Indonesia', NULL),
('BKK', 'Suvarnabhumi', 'Thailand', NULL),
('BNA', 'Nashville International', 'United States', 'TN'),
('BOG', 'El Dorado International', 'Colombia', NULL),
('BOM', 'Chhatrapati Shivaji Maharaj', 'India', NULL),
('BSB', 'Brasilia International', 'Brazil', NULL),
('BTV', 'Burlington International', 'United States', 'VT'),
('CAN', 'Guangzhou Baiyun International', 'China', NULL),
('CDG', 'Charles de Gaulle Airport', 'France', NULL),
('CGK', 'Soekarno-Hatta', 'Indonesia', NULL),
('CLT', 'Charlotte Douglas', 'United States', 'NC'),
('CUN', 'Cancun International', 'Mexico', NULL),
('DCA', 'Ronald Reagan Washington', 'United States', 'DC'),
('DEN', 'Denver International', 'United States', 'CO'),
('DFW', 'Dallas Fort Worth International', 'United States', 'TX'),
('DOH', 'Hamad ', 'Qatar', NULL),
('DTW', 'Detriot Metropolitan Wayne', 'United States', 'MI'),
('DXB', 'Dubai International', 'UAE', NULL),
('DYU', 'Dushanbe International', 'Tajikstan', NULL),
('EWR', 'Newark Liberty International', 'United States', 'NJ'),
('EZE', 'Ministro Pistarini International', 'Argentina', NULL),
('FCO', 'Rome Fiumicino', 'Italy', NULL),
('FRA', 'Frankfurt am Main', 'Germany', NULL),
('GMP', 'Gimpo International Airport', 'South Korea', NULL),
('GUA', 'La Aurora International', 'Guatemala', NULL),
('HEL', 'Helsinki Airport', 'Finland', NULL),
('HND', 'Tokyo Haneda Airport', 'Japan', NULL),
('HOU', 'William P Hobby Airport', 'United States', 'TX'),
('HRK', 'Kharkiv International', 'Ukraine', NULL),
('HYD', 'Rajiv Gandhi International', 'India', NULL),
('IAD', 'Washington Dulles International', 'United States', 'DC'),
('IAH', 'George Bush Intercontinental', 'United States', 'TX'),
('ICN', 'Incheon International', 'South Korea', NULL),
('IST', 'Istanbul Airport', 'Turkey', NULL),
('ITM', 'Osaka Itami Airport', 'Japan', NULL),
('JED', 'King Abdulaziz', 'Saudi Arabia', NULL),
('JFK', 'JFK', 'United States', 'NY'),
('KBP', 'Boryspil', 'Ukraine', NULL),
('KEF', 'Keflavik Airport', 'Iceland', NULL),
('KRK', 'Krakow John Paul II', 'Poland', NULL),
('KTW', 'Katcwice', 'Poland', NULL),
('KUL', 'Kuala Lumpur', 'Malaysia', NULL),
('LAS', 'Harry Reid International', 'United States', 'NV'),
('LAX', 'Los Angeles International', 'United States', 'CA'),
('LEX', 'Blue Grass Airport', 'United States', 'KY'),
('LGA', 'LaGuardia Airport', 'United States', 'NY'),
('LHR', 'Heathrow Airport', 'United Kingdom', NULL),
('LIM', 'Jorge Chavez International', 'Peru', NULL),
('LIS', 'Humberto Delgado', 'Portugal', NULL),
('LPD', 'El Alto International', 'Bolivia', NULL),
('LWO', 'Danylo-Halytskyi International', 'Ukraine', NULL),
('MCO', 'Orlando International', 'United States', 'FL'),
('MDW', 'Midway', 'United States', 'IL'),
('MEX', 'Mexico City International', 'Mexico', NULL),
('MIA', 'Miami International', 'United States', 'FL'),
('MNL', 'Ninoy Aquino', 'Philippines', NULL),
('MUC', 'Munich Airport', 'Germany', NULL),
('MVD', 'Carrasco International', 'Uruguay', NULL),
('MXP', 'Malpensa Airport', 'Italy', NULL),
('ODS', 'Odesa International', 'Ukraine', NULL),
('ORD', 'O''hare International', 'United States', 'IL'),
('OTP', 'Henri Coanda International', 'Romania', NULL),
('PEK', 'Beijing Capital International', 'China', NULL),
('PTY', 'Tocumen International', 'Panama', NULL),
('PVG', 'Shanghai Pudong International', 'China', NULL),
('RIX', 'Riga International', 'Latvia', NULL),
('RUH', 'King Khalid', 'Saudi Arabia', NULL),
('SCL', 'Arturo Merino Benitez', 'Chile', NULL),
('SEA', 'Seattle-Tacoma International', 'United States', 'WA'),
('SFO', 'San Fransisco', 'United States', 'CA'),
('SIN', 'Singapore Changi Airport', 'Singapore', NULL),
('SJO', 'Juan Santamaria International', 'Costa Rica', NULL),
('SLC', 'Salt Lake City International', 'United States', 'UT'),
('SOF', 'Vasil Levski Sofia', 'Bulgaria', NULL),
('SZX', 'Shenzhen Bao''an', 'China', NULL),
('TAS', 'Tashkent International', 'Uzbekistan', NULL),
('TGU', 'Toncontin Airport', 'Honduras', NULL),
('TPA', 'Tampa International', 'United States', 'FL'),
('TSE', 'Astana Internnational', 'Kazakhstan', NULL),
('UIO', 'Mariscal Sucre International', 'Ecuador', NULL),
('ULN', 'Buyant Ukhaa International', 'Mongolia', NULL),
('VIE', 'Vienna Airport', 'Austria', NULL),
('VNO', 'Vilnius International Airport', 'Lithuania', NULL),
('WAW', 'Lotnisko Chopina Warszawa', 'Poland', NULL),
('YEG', 'Edmonton International', 'Canada', NULL),
('YHZ', 'Halifax Stanfield International', 'Canada', NULL),
('YLW', 'Kelowna International', 'Canada', NULL),
('YOW', 'Ottawa International', 'Canada', NULL),
('YUL', 'Montreal-Trudeau International', 'Canada', NULL),
('YVR', 'Vancouver International', 'Canada', NULL),
('YWG', 'Armstrong Richardson International', 'Canada', NULL),
('YYC', 'Calgary International', 'Canada', NULL),
('YYZ', 'Totonto Pearson International', 'Canada', NULL),
('ZAG', 'Zagreb Airport', 'Croatia', NULL);

INSERT INTO Airline
VALUES
('2I', 'Star Peru', 'Peru'),
('2K', 'Avianca Ecuador', 'Ecuador'),
('3H', 'Air Inuit', 'Canada'),
('4N', 'Air North', 'Canada'),
('5U', 'TAG', 'Guatemala'),
('6E', 'IndiGo', 'India'),
('6L', 'Aklak Air', 'Canada'),
('7C', 'Jeju Air', 'South Korea'),
('7J', 'Tajik Air', 'Tajikstan'),
('7P', 'Air Panama', 'Panama'),
('A3', 'Aegean Airlines', 'Greece'),
('AA', 'American Airlines', 'United States'),
('AC', 'Air Canada', 'Canada'),
('AF', 'Air France', 'France'),
('AI', 'Air India', 'India'),
('AK', 'AirAsia', 'Malaysia'),
('AM', 'Aeromexico', 'Mexico'),
('AS', 'Alaska Airlines', 'United States'),
('AV', 'Avianca', 'Colombia'),
('AY', 'Finnair', 'Finland'),
('B6', 'JetBlue', 'United States'),
('BA', 'British Airways', 'United Kingdom'),
('BQ', 'Sky Alps', 'Italy'),
('BT', 'AirBaltic', 'Latvia'),
('CA', 'Air China', 'China'),
('CZ', 'China Southern Airlines', 'China'),
('DD', 'Nok Air', 'Thailand'),
('DL', 'Delta Air Lines', 'United States'),
('EK', 'Emirates', 'UAE'),
('EW', 'Eurowings', 'Germany'),
('F9', 'Frontier Airlines', 'United States'),
('FB', 'Bulgaria Air', 'Bulgaria'),
('FI', 'Icelandair', 'Iceland'),
('FO', 'Flybondi', 'Argentina'),
('FS', 'FlyArystan', 'Kazakhstan'),
('G3', 'Gol Transportes Aereos', 'Brazil'),
('G4', 'Allegiant Air', 'United States'),
('H2', 'SKY Airline', 'Chile'),
('HU', 'Hainan Airlines', 'China'),
('HW', 'North-Weight Airways', 'Canada'),
('HY', 'Uzbekistan Airways', 'Uzbekistan'),
('ID', 'Batik Air', 'Indonesia'),
('JV', 'Bearskin Airlines', 'Canada'),
('KE', 'Korean Air', 'South Korea'),
('KL', 'KLM', 'Netherlands'),
('LH', 'Lufthansa', 'Germany'),
('LO', 'Lot Polish Airlines', 'Poland'),
('LR', 'Avianca Costa Rica', 'Costa Rica'),
('M0', 'Aero Mongolia', 'Mongolia'),
('MU', 'China Eastern Airlines', 'China'),
('MX', 'Breeze Airways', 'United States'),
('N3', 'Aeromas', 'Uruguay'),
('NH', 'All Nippon Airways', 'Japan'),
('NQ', 'Air Japan', 'Japan'),
('O4', 'Andes', 'Argentina'),
('OB', 'Boliviana de Aviacion', 'Bolivia'),
('OE', 'FlyOne Romania', 'Romania'),
('OO', 'Skywest Airlines', 'United States'),
('OS', 'Austrian Airlines', 'Austria'),
('OU', 'Croatia Airlines', 'Croatia'),
('PC', 'Pegasus Airlines', 'Turkey'),
('PR', 'Philippine Airlines', 'Philippines'),
('QC', 'Citilink', 'Indonesia'),
('QK', 'Jazz Aviation', 'Canada'),
('QR', 'Qatar Airways', 'Qatar'),
('QU', 'Skyline Express', 'Ukraine'),
('RV', 'Air Canada Rouge', 'Canada'),
('RX', 'Riyadh Air', 'Saudi Arabia'),
('SQ', 'Singapore Airlines', 'Singapore'),
('SV', 'Saudia', 'Saudi Arabia'),
('SY', 'Sun Country Airlines', 'United States'),
('T5', 'Turkmenistan Airlines', 'Turkmenistan'),
('TP', 'TAP Air Portugal', 'Portugal'),
('UA', 'United Airlines', 'United States'),
('VB', 'Viva', 'Mexico'),
('WC', 'Avianca Honduras', 'Honduras'),
('WN', 'Southwest Airlines', 'United States'),
('X9', 'Avion Express', 'Lithuania'),
('XP', 'Avelo Airlines', 'United States'),
('XZ', 'AeroItalia', 'Italy'),
('YN', 'Air Creebec', 'Canada'),
('ZP', 'Paranair', 'Paraguay');
